name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: Install
        run: |
          npm install
      - name: Test
        run: |
          npm test
      - name: Bundle
        run: |
          npm run-script bundle
          cp style.css dist/style.css
          cat index.html | sed 's#dist/index.js#index.js#' > dist/index.html
      - name: debug
        run: |
          pwd
          ls -hal
          ls -hal dist
          git status
          cat dist/index.html
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
          ssh-key: ${{ secrets.DEPLOY_KEY_2025 }}
